language: ruby
rvm: 2.1
env:
  global:
    - secure: dGmVBMCm8KfY1WjzbrXcBg0BL4tB1buTv7UVnJtNl19bAqe9acT71LnoPTOw7eitnu3UW5rgvJfEBT2TEJOjnLpaqmEiK8Oa8FboklG281fsMevrabz+y2ujc0TIQfsNNbFBahE82SacwjbZ4EM5iSR9En/cExqUwQ1VjDTW/Bs=
script:
- scripts/build.sh
before_deploy:
- echo "//registry.npmjs.org/:_authToken=${NPM_KEY}" >> .npmrc
deploy:
- provider: script
  skip_cleanup: true
  script: npm publish build/pact-mock-service-darwin --access public
  on:
    branch: master
    tags: true
- provider: script
  skip_cleanup: true
  script: npm publish build/pact-mock-service-linux-ia32 --access public
  on:
    branch: master
    tags: true
- provider: script
  skip_cleanup: true
  script: npm publish build/pact-mock-service-linux-x64 --access public
  on:
    branch: master
    tags: true
- provider: script
  skip_cleanup: true
  script: npm publish build/pact-mock-service-win32 --access public
  on:
    branch: master
    tags: true
