language: ruby
rvm: 2.1
env:
  global:
    - secure: QEplQuDirqkuwWEQTvRbnf264nR/f8u8i4HyEPybyutjzcR3urNruOaFGIVQoavhijF3fDPHIJyB0pMF0VGLTlPwrmuT35gCh3cEPJbunNZ8efofbvsO7RP4mcwVyT7m/hbayTcsSXe+cu8//BtNh9f6ykCkHmZ6d6x8l6XVJoQ=
install:
- npm install
before_script:
- npm test
script:
- scripts/build.sh
before_deploy:
- echo "@pact-foundation:registry=https://registry.npmjs.org/" > .npmrc
- echo "//registry.npmjs.org/:_authToken=${NPM_KEY}" >> .npmrc
- echo "//registry.npmjs.org/:username=pact-foundation" >> .npmrc
- echo "//registry.npmjs.org/:email=pact-foundation@googlegroups.com" >> .npmrc
- echo "//registry.npmjs.org/:always-auth=true" >> .npmrc
- cat .npmrc
- cp .npmrc build/pact-mock-service-darwin/
- cp .npmrc build/pact-mock-service-win32/
- cp .npmrc build/pact-mock-service-linux-ia32/
- cp .npmrc build/pact-mock-service-linux-x64/
deploy:
- provider: script
  skip_cleanup: true
  script: cd build/pact-mock-service-darwin/ && npm publish .
- provider: script
  skip_cleanup: true
  script: cd build/pact-mock-service-linux-ia32/ && npm publish .
- provider: script
  skip_cleanup: true
  script: cd build/pact-mock-service-linux-x64/ && npm publish .
- provider: script
  skip_cleanup: true
  script: cd build/pact-mock-service-win32/ && npm publish .
- provider: script
  skip_cleanup: true
  script: npm publish .
