language: ruby
rvm: 2.1
env:
  global:
    - secure: dGmVBMCm8KfY1WjzbrXcBg0BL4tB1buTv7UVnJtNl19bAqe9acT71LnoPTOw7eitnu3UW5rgvJfEBT2TEJOjnLpaqmEiK8Oa8FboklG281fsMevrabz+y2ujc0TIQfsNNbFBahE82SacwjbZ4EM5iSR9En/cExqUwQ1VjDTW/Bs=
before_install:
- echo "@pact-foundation:registry=https://registry.npmjs.org/" > .npmrc
- echo "//registry.npmjs.org/:_authToken=${NPM_KEY}" >> .npmrc
- echo "//registry.npmjs.org/:username=pact-foundation" >> .npmrc
- echo "//registry.npmjs.org/:email=pact-foundation@googlegroups.com" >> .npmrc
- echo "//registry.npmjs.org/:always-auth=true" >> .npmrc
install:
- npm install
before_script:
- npm test
script:
- scripts/build.sh
- cp .npmrc build/pact-mock-service-darwin/
- cp .npmrc build/pact-mock-service-win32/
- cp .npmrc build/pact-mock-service-linux-ia32/
- cp .npmrc build/pact-mock-service-linux-x64/
deploy:
- provider: script
  skip_cleanup: true
  script: npm publish build/pact-mock-service-darwin/
  on:
    branch: master
    tags: true
- provider: script
  skip_cleanup: true
  script: npm publish build/pact-mock-service-linux-ia32/
  on:
    branch: master
    tags: true
- provider: script
  skip_cleanup: true
  script: npm publish build/pact-mock-service-linux-x64/
  on:
    branch: master
    tags: true
- provider: script
  skip_cleanup: true
  script: npm publish build/pact-mock-service-win32/
  on:
    branch: master
    tags: true
- provider: script
  skip_cleanup: true
  script: npm publish .
  on:
    branch: master
    tags: true
